#!/bin/sh /etc/rc.common
# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>

START=90
STOP=10

CONFIG="filerun"
KOD_NGINX_CONFIG="/etc/nginx/conf.d/filerun.conf"
dbpasswd=$(uci -q get $CONFIG.main.dbpasswd)

gen_nginx_config() {
	port=$(uci -q get $CONFIG.main.port)
	kodomain=$(uci -q get $CONFIG.main.kodomain)
sed -i "s?listen [0-9]*;?listen $port;?g" $KOD_NGINX_CONFIG
[ $kodomain ] && {
	sed -i "s?server_name .*?server_name $kodomain;?g" $KOD_NGINX_CONFIG
	}
}

gen_php_config() {
	memory_limit=$(uci -q get $CONFIG.main.memory_limit)
	upload_max_filesize=$(uci -q get $CONFIG.main.upload_max_filesize)

	sed -i "s/memory_limit.*/memory_limit = $memory_limit/g" /etc/php7/custom.ini
	sed -i "s/post_max_size.*/post_max_size = $upload_max_filesize/g" /etc/php7/custom.ini
	sed -i "s/upload_max_filesize.*/upload_max_filesize = $upload_max_filesize/g" /etc/php7/custom.ini
	sed -i "s/client_max_body_size.*/client_max_body_size $upload_max_filesize;/g" $KOD_NGINX_CONFIG
}

start() {
	ENABLED=$(uci -q get $CONFIG.main.enable)
	[ "$ENABLED" = "0" ] && return 0
	gen_php_config
	/etc/init.d/php7-fpm start
	gen_nginx_config
	/etc/init.d/nginx reload
	[ -f "/usr/local/mysql" ] && chown mariadb:mariadb /usr/data/mysql/* || mysql_install_db
	mysqladmin -uroot -proot password $dbpasswd
	/etc/init.d/mysqld start
}

stop() {
	/etc/init.d/php7-fpm stop
	/etc/init.d/mysqld stop
	[ "`pgrep php-fpm`" ] && {
	killall -9 php-fpm
	}
	[ "`pgrep mysqld`" ] && {
	killall mysqld
	}
}
